export const DEFAULT_THEMES: string[] = ['light', 'dark'];

export const  COMMON_LANGUAGES: {[key: string]: string} = {
  none: 'Auto-detect',
  apache: 'Apache',
  bash: 'Bash',
  cs: 'C#',
  cpp: 'C++',
  css: 'CSS',
  coffeescript: 'CoffeeScript',
  diff: 'Diff',
  go: 'Go',
  html: 'HTML, XML',
  http: 'HTTP',
  json: 'JSON',
  java: 'Java',
  javascript: 'JavaScript',
  kotlin: 'Kotlin',
  less: 'Less',
  lua: 'Lua',
  makefile: 'Makefile',
  markdown: 'Markdown',
  nginx: 'Nginx',
  objectivec: 'Objective-C',
  php: 'PHP',
  perl: 'Perl',
  properties: 'Properties',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  scss: 'SCSS',
  sql: 'SQL',
  shell: 'Shell Session',
  swift: 'Swift',
  toml: 'TOML, also INI',
  typescript: 'TypeScript',
  yaml: 'YAML',
  plaintext: 'Plaintext'
};